// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/member": {
            "get": {
                "description": "Gets all members which are saved in the database",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Member"
                ],
                "summary": "Get all Members",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/entities.Member"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_pulsone21_powner_internal_server_response.ApiResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_pulsone21_powner_internal_server_response.ApiResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Get all Members",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Member"
                ],
                "summary": "Create a Member",
                "parameters": [
                    {
                        "description": "Member request",
                        "name": "MemberRequest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entities.MemberRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/entities.Member"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_pulsone21_powner_internal_server_response.ApiResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_pulsone21_powner_internal_server_response.ApiResponse"
                        }
                    }
                }
            }
        },
        "/member/{id}": {
            "get": {
                "description": "gets a member by its id, which is the primary key in the database",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Member"
                ],
                "summary": "gets a member by its id",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Member Id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/entities.Member"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_pulsone21_powner_internal_server_response.ApiResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_pulsone21_powner_internal_server_response.ApiResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Updates a member by its id, which is the primary key in the database",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Member"
                ],
                "summary": "Updates member by its id",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Member Id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Member request",
                        "name": "MemberRequest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entities.MemberRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/entities.Member"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_pulsone21_powner_internal_server_response.ApiResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_pulsone21_powner_internal_server_response.ApiResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Deletes a member by its id, which is the primary key in the database",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Member"
                ],
                "summary": "Deletes member by its id",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Member Id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/entities.Member"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_pulsone21_powner_internal_server_response.ApiResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_pulsone21_powner_internal_server_response.ApiResponse"
                        }
                    }
                }
            }
        },
        "/member/{member_id}/skill/{skill_id}": {
            "post": {
                "description": "adds a skill by its id to the member by the member id, you can set the rating directly with the query param rating",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Member"
                ],
                "summary": "adds a skill to a member",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Skill Id",
                        "name": "skill_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Member Id",
                        "name": "member_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "rating",
                        "name": "rating",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/entities.Member"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_pulsone21_powner_internal_server_response.ApiResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_pulsone21_powner_internal_server_response.ApiResponse"
                        }
                    }
                }
            }
        },
        "/member/{member_id}/skill/{skill_id}/{rating}": {
            "post": {
                "description": "updates the skillrating by the skill by the id from the member by the member id",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Member"
                ],
                "summary": "updates the skillrating from a member",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Skill Id",
                        "name": "skill_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Member Id",
                        "name": "member_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "rating",
                        "name": "rating",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/entities.Member"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_pulsone21_powner_internal_server_response.ApiResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_pulsone21_powner_internal_server_response.ApiResponse"
                        }
                    }
                }
            }
        },
        "/skill": {
            "get": {
                "description": "Gets all kill which are saved in the database",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Skill"
                ],
                "summary": "Get all skill",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/entities.Skill"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_pulsone21_powner_internal_server_response.ApiResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_pulsone21_powner_internal_server_response.ApiResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Get all Skills",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Skill"
                ],
                "summary": "Create a Skill",
                "parameters": [
                    {
                        "description": "Member request",
                        "name": "SkillRequest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entities.MemberRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/entities.Skill"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_pulsone21_powner_internal_server_response.ApiResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_pulsone21_powner_internal_server_response.ApiResponse"
                        }
                    }
                }
            }
        },
        "/skill/{id}": {
            "get": {
                "description": "gets a Skill by its id, which is the primary key in the database",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Skill"
                ],
                "summary": "gets a Skill by its id",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Skill Id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/entities.Skill"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_pulsone21_powner_internal_server_response.ApiResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_pulsone21_powner_internal_server_response.ApiResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Updates a Skill by its id, which is the primary key in the database",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Skill"
                ],
                "summary": "Updates Skill by its id",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Skill Id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Member request",
                        "name": "SkillRequest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entities.MemberRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/entities.Skill"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_pulsone21_powner_internal_server_response.ApiResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_pulsone21_powner_internal_server_response.ApiResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Deletes a Skill by its id, which is the primary key in the database",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Skill"
                ],
                "summary": "Deletes Skill by its id",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Skill Id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/entities.Skill"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_pulsone21_powner_internal_server_response.ApiResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_pulsone21_powner_internal_server_response.ApiResponse"
                        }
                    }
                }
            }
        },
        "/team": {
            "get": {
                "description": "Gets all teams which are saved in the database",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Team"
                ],
                "summary": "Get all teams",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/entities.Team"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_pulsone21_powner_internal_server_response.ApiResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_pulsone21_powner_internal_server_response.ApiResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Get all teams",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Team"
                ],
                "summary": "Create a team",
                "parameters": [
                    {
                        "description": "Team request",
                        "name": "teamRequest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entities.TeamRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/entities.Team"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_pulsone21_powner_internal_server_response.ApiResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_pulsone21_powner_internal_server_response.ApiResponse"
                        }
                    }
                }
            }
        },
        "/team/{id}": {
            "get": {
                "description": "gets a team by its id, which is the primary key in the database",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Team"
                ],
                "summary": "gets a team by its id",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "team Id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/entities.Team"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_pulsone21_powner_internal_server_response.ApiResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_pulsone21_powner_internal_server_response.ApiResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Updates a team by its id, which is the primary key in the database",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Team"
                ],
                "summary": "Updates team by its id",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "team Id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Team request",
                        "name": "teamRequest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entities.TeamRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/entities.Team"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_pulsone21_powner_internal_server_response.ApiResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_pulsone21_powner_internal_server_response.ApiResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Deletes a team by its id, which is the primary key in the database",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Team"
                ],
                "summary": "Deletes team by its id",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "team Id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/entities.Team"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_pulsone21_powner_internal_server_response.ApiResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_pulsone21_powner_internal_server_response.ApiResponse"
                        }
                    }
                }
            }
        },
        "/team/{team_id}/member/{member_id}": {
            "post": {
                "description": "Updates a member by its id, which is the primary key in the database",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Team"
                ],
                "summary": "Adds a member to a team",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Member Id",
                        "name": "member_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Team Id",
                        "name": "team_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/entities.Team"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_pulsone21_powner_internal_server_response.ApiResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_pulsone21_powner_internal_server_response.ApiResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Removes a member by its id from the team given by the id.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Team"
                ],
                "summary": "remove a member from a team",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Member Id",
                        "name": "member_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Team Id",
                        "name": "team_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/entities.Team"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_pulsone21_powner_internal_server_response.ApiResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_pulsone21_powner_internal_server_response.ApiResponse"
                        }
                    }
                }
            }
        },
        "/team/{team_id}/skill/{skill_id}": {
            "post": {
                "description": "Adds a skill by its id to the team by the team id",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Team"
                ],
                "summary": "Adds a skill to a team",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Skill Id",
                        "name": "skill_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Team Id",
                        "name": "team_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/entities.Team"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_pulsone21_powner_internal_server_response.ApiResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_pulsone21_powner_internal_server_response.ApiResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "removes a skill by its id from the team by the team id",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Team"
                ],
                "summary": "removes a skill from a team",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Skill Id",
                        "name": "skill_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Team Id",
                        "name": "team_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/entities.Team"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_pulsone21_powner_internal_server_response.ApiResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_pulsone21_powner_internal_server_response.ApiResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "entities.Member": {
            "type": "object",
            "properties": {
                "age": {
                    "type": "integer"
                },
                "createdAt": {
                    "type": "string"
                },
                "deletedAt": {
                    "$ref": "#/definitions/gorm.DeletedAt"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "skills": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entities.SkillRating"
                    }
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "entities.MemberRequest": {
            "type": "object",
            "properties": {
                "age": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "entities.Skill": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "deletedAt": {
                    "$ref": "#/definitions/gorm.DeletedAt"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "importance": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "type": {
                    "type": "integer"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "entities.SkillRating": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "deletedAt": {
                    "$ref": "#/definitions/gorm.DeletedAt"
                },
                "id": {
                    "type": "integer"
                },
                "member_id": {
                    "type": "integer"
                },
                "rating": {
                    "type": "integer"
                },
                "skill": {
                    "$ref": "#/definitions/entities.Skill"
                },
                "skill_id": {
                    "type": "integer"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "entities.Team": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "deletedAt": {
                    "$ref": "#/definitions/gorm.DeletedAt"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "members": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entities.Member"
                    }
                },
                "name": {
                    "type": "string"
                },
                "skills": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entities.Skill"
                    }
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "entities.TeamRequest": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "github_com_pulsone21_powner_internal_server_response.ApiResponse": {
            "type": "object",
            "properties": {
                "data": {},
                "error": {},
                "statusCode": {
                    "type": "integer"
                }
            }
        },
        "gorm.DeletedAt": {
            "type": "object",
            "properties": {
                "time": {
                    "type": "string"
                },
                "valid": {
                    "description": "Valid is true if Time is not NULL",
                    "type": "boolean"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Powner API Documentation",
	Description:      "This is the api documentation of the powner application.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
